### ISSUE TITLE
has/contains Method in PubSubCache

### ISSUE THREAD

**Issue by W3ldoo** [JackWhite20/JaPS#1]
Please make a method to check if a specific is in the pubsubcache

**Comment by JackWhite20** [comment]
Oh yea, I'll make it quick :)

**Comment by W3ldoo** [comment]
Danke! :)

**Comment by JackWhite20** [comment]
The [new release](https://github.com/JackWhite20/JaPS/releases) is live :)

Keep in mind to update the server as well.

The usage:
```java
try {
	System.out.println("Has: " + pubSubCache.has("test").get());
} catch (InterruptedException | ExecutionException e) {
	e.printStackTrace();
}
```

**Comment by W3ldoo** [comment]
Thanks for doing that so fast. 
That is so useful.

**Comment by JackWhite20** [comment]
No problem, if you have any trouble contact me.
