### ISSUE TITLE
Error -> disconnect (publisher, subscriber and cache no longer working)

### ISSUE THREAD

**Issue by MarvinErkes** [JackWhite20/JaPS#2]
Hello,

if something wrong get published into japs,
it disconnect all publishers, subscribers.
And JaPS prints out a error(http://hastebin.com/adugiqozel.pl),
but without a hint what crashs it!
Please print out what´s wrong and let the publishers and subscribers automatically reconnect, when a error occurs.

Thanks

**Comment by JackWhite20** [comment]
Could you please test if this version fixes the problem?

A big update with things like better error reporting and much more is planned.

[japs-server-2.2.2.zip](https://github.com/JackWhite20/JaPS/files/511499/japs-server-2.2.2.zip)

**Comment by MarvinErkes** [comment]
It will take a while.
I will contact you in this issue,
if its crashs again.

**Comment by MarvinErkes** [comment]
What is changed is different to the version before?

**Comment by JackWhite20** [comment]
At the moment only a null check i forgot in the broadcast part.

**Comment by MarvinErkes** [comment]
oh. i think that this will fix it.

**Comment by JackWhite20** [comment]
Yea, keep in mind that a new version is on its way. 
Should be released in the next few days.
Could I ask you for what type of project you are using JaPS?

**Comment by MarvinErkes** [comment]
Next error..
http://hastebin.com/kunuvulive.php

Yeah, it´s a minecraft project.

**Comment by JackWhite20** [comment]
Ok, cool.

Sorry for the inconvenience, i will build a hot fix now.

Are you broadcasting messages directly after the connect?

**Comment by MarvinErkes** [comment]
mhm. yes.

**Comment by JackWhite20** [comment]
For now you can simply start broadcasting stuff a bit later, so that all clients are connected first before you broadcast messages.

**Comment by MarvinErkes** [comment]
Ok. I´ve fixed it already.

**Comment by MarvinErkes** [comment]
Can you do this please. I really need it.

**Comment by JackWhite20** [comment]
Could you please test this version?
[japs-server-2.2.2.zip](https://github.com/JackWhite20/JaPS/files/511619/japs-server-2.2.2.zip)

**Comment by MarvinErkes** [comment]
I will test it for now. Please wait for my test results.

**Comment by JackWhite20** [comment]
Is it fixed with the last version?
