### ISSUE TITLE
wrong constructor used?

### ISSUE THREAD

**Issue by canatoly** [JackWhite20/JaPS#4]
sorry for my english 

Using constructor with one param while broadcasting to cluster instances "new JSONObject(data)" and passing JSONObject as argument leads to empty new JSONObject, i.e. data is lost

de/jackwhite20/japs/server/JaPSServer.java:222
de/jackwhite20/japs/server/JaPSServer.java:243

should it be used something like this one JSONObject(JSONObject jo, String[] names) ?

**Comment by JackWhite20** [comment]
Hey, thanks for the report!

I will commit a fix to use `new JSONObject(jsonObject.toMap())` so that it is a deep clone and not only a shallow clone as it would be with `new JSONObject(original, JSONObject.getNames(original))`.

**Comment by JackWhite20** [comment]
Do you have JaPS somewhere running in a cluster mode where you can maybe test a new version?

**Comment by canatoly** [comment]
yes, we trying to use JaSP on 3-node cluster, to sync common data and notify of it's changing

by the way it will be very helpfull if we have an event| builtin channel to notify participants of manipulations with common cache, i.e "was put", "was expired" or something like this. To not to duplicate cache manipulations with own notifications

**Comment by JackWhite20** [comment]
Oh okay, cool to hear that :)

Thats a great idea, maybe I can implement that when i have a little bit more time, but i noted it down!

It would be awesome if you could test this version with the 3 node cluster. If it works, I can release a new version.

[japs-server.zip](https://github.com/JackWhite20/JaPS/files/1560430/japs-server.zip)

**Comment by canatoly** [comment]
>japs-server.zip
it's ok now, all 3 nodes receive the complete data, thanx
