### ISSUE TITLE
cache synchronization after the node is up

### ISSUE THREAD

**Issue by canatoly** [JackWhite20/JaPS#6]
hello again )

syncronized cache is not accesible to node which is up after puting something in cache  

cofiguration:
3 node cluster, each configured to see to others

steps to reproduce
1. start only 2 nodes
2. put something in cache (set a 1)
3. start third node
4. try to get value on third node (get a)

i think that after new node was looked up it should receive complete cache from one of the already running one

thanx

**Comment by JackWhite20** [comment]
Oh jesus, yes. I will push a fix in the evening that newly started JaPS Server in a cluster will request the current cache state from one of the already available JaPS servers.

Thanks for your reports!

**Comment by JackWhite20** [comment]
This version will sync the cache when started in a cluster environment. It also syncs the expiration values from the keys.

I have tested it with two JaPS servers. It would be great if you could test it with your JaPS cluster too and tell me if it works as expected.

[japs-server-cache-sync.zip](https://github.com/JackWhite20/JaPS/files/1563525/japs-server-cache-sync.zip)

**Comment by JackWhite20** [comment]
Could you already test it?

**Comment by canatoly** [comment]
sory for make you wait, there were weekends.
I've tested it now, everithing seams to work as expected.  Tested late joining node and restarting already runing, every node got at the end all cache
thanx

**Comment by JackWhite20** [comment]
Okay perfect.

Fixed in b61b1abcfe6bcfb498b15820ef0ea8c29fb6e049.
