### ISSUE TITLE
netty usage

### ISSUE THREAD

**Issue by canatoly** [JackWhite20/JaPS#8]
reconnecting leads to many EventLoopGroup threads and then to "many opened files"

de.jackwhite20.japs.shared.nio.NioSocketClient#connect

instance of Bootstrap should be created only once, not on every connect|reconnect

please, move it to constructor 
```
private Bootstrap bootstrap;
...
bootstrap = new Bootstrap()
                .group(PipelineUtils.newEventLoopGroup(1))
                .channel(PipelineUtils.getChannel())
                .handler(new ClientChannelInitializer(this))
                .option(ChannelOption.TCP_NODELAY, true)
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, CONNECT_TIMEOUT);
```

and in "connect()" method leave just 
`bootstrap.connect(host, port)`

**Comment by JackWhite20** [comment]
Hey, I will look into that.

**Comment by JackWhite20** [comment]
Could you please test this version in the next few hours so I can push a release in the evening?

There also two system properties to set the connect timeout (japs.connect.timeout) and the reconnect delay (japs.reconnect.delay). For example -Djaps.connect.timeout=4000 sets the connect timeout to 4 seconds.


[japs-client.zip](https://github.com/JackWhite20/JaPS/files/1883435/japs-client.zip)

**Comment by canatoly** [comment]
ok, i will

**Comment by canatoly** [comment]
it seams ok now

**Comment by JackWhite20** [comment]
Okay thanks. I have profiled it too and everything should be fine. If not, reopen this issue or create a new one ;)

Release should come in about 3 hours.
